//------------------------------------------------------------------------
// Copyright(c) 2025 Void Audio.
//------------------------------------------------------------------------

#pragma once

#include "pluginterfaces/base/fplatform.h"

// Plain project version file generated by cmake 
#include "projectversion.h"

#define stringOriginalFilename	"Rend.vst3"
#if SMTG_PLATFORM_64
#define stringFileDescription	"Rend VST3 (64Bit)"
#else
#define stringFileDescription	"Rend VST3"
#endif
#define stringCompanyName		"Void Audio\0"
#define stringLegalCopyright	"Copyright(c) 2025 Void Audio."
#define stringLegalTrademarks	"VST is a trademark of Steinberg Media Technologies GmbH"
