name: Build Native

on:
  push:
    branches:
      - FKernels   

env:
  PROJECT_NAME: TemplateProject

jobs:
  build:
    name: Build-native-plugin
    runs-on: windows-latest   

    steps:
    - name: Check out repository
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Get VST3 SDK
      run: |
        cd iPlug2/Dependencies/IPlug
        ./download-iplug-sdks.sh
      shell: bash

    - name: Get Prebuilt Libs
      run: |
        cd iPlug2/Dependencies
        ./download-prebuilt-libs.sh
      shell: bash

    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v2

    - name: Build Windows VST3
      run: |
        cd ${{env.PROJECT_NAME}}\scripts
        .\makedist-win.bat full zip
      shell: pwsh

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{env.PROJECT_NAME}}-win
        path: ${{env.PROJECT_NAME}}/build-win/out
